apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lb-inter-node-exporter
  labels:
    app.kubernetes.io/name: lb-inter-node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lb-inter-node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lb-inter-node-exporter
    spec:
      containers:
      - name: lb-inter-node-exporter
        image: lb-inter-node-exporter:dev
        command: ["lb-inter-node-exporter", "-i=net0", "--xdp-mode=skb"]
        securityContext:
          privileged: true
        ports:
        - name: metrics
          containerPort: 61678
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
      tolerations:
        - operator: Exists
      serviceAccountName: lb-inter-node-exporter
      hostNetwork: true
      hostPID: true
