apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lb-inter-node-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lb-inter-node-exporter
subjects:
  - kind: ServiceAccount
    name: lb-inter-node-exporter
    namespace: kube-system
