apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lb-inter-node-exporter
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
